# Overall theme outline
title: Joshua Calzadillas
logo: /assets/img/logo.png
description: Research projects website
show_downloads: false
theme: jekyll-theme-minimal


# Navbar
header_pages:
  - index.md
  - research.md
  - publications.md
  - about.md